# Generated by Django 5.1.15 on 2026-06-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectplan',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
