# Generated by Django 5.1.15 on 2026-06-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_phase3_qa_gates'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='has_database',
            field=models.BooleanField(default=False),
        ),
    ]
