# Generated by Django 5.1.15 on 2026-06-01 23:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=80)),
                ('status', models.CharField(default='completed', max_length=30)),
                ('input', models.JSONField(default=dict)),
                ('output', models.JSONField(default=dict)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('logs', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
