# Generated by Django 5.1.15 on 2026-06-05 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0002_subscription_deployment_default'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QAChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_approved', models.BooleanField(default=False)),
                ('roadmap_completed', models.BooleanField(default=False)),
                ('no_blocking_tickets', models.BooleanField(default=False)),
                ('url_reachable', models.BooleanField(default=False)),
                ('client_page_reviewed', models.BooleanField(default=False)),
                ('notes_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deployment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qa_checklist', to='deployments.deployment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_checklists_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
