# Generated by Django 5.1.15 on 2026-06-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0003_phase3_qa_gates'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='admin_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
