# Generated by Django 5.1.15 on 2026-06-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='client_visible',
            field=models.BooleanField(default=True),
        ),
    ]
