# Generated by Django 5.1.15 on 2026-06-01 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_url', models.URLField(blank=True)),
                ('zip_file_name', models.CharField(blank=True, max_length=240)),
                ('status', models.CharField(default='analyzed', max_length=30)),
                ('detected_structure', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack', models.JSONField(default=list)),
                ('frameworks', models.JSONField(default=list)),
                ('risks', models.JSONField(default=list)),
                ('score', models.PositiveSmallIntegerField(default=70)),
                ('recommendation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='projects.project')),
                ('project_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imports.projectimport')),
            ],
        ),
    ]
